title: Haitham Qudaih
description: "Front End Developer at tajawal — tech guy with an entrepreneurial spirit and knack for getting things done"
url: "https://haithamq.github.io"
author: "Haitham Qudaih"
keywords: "haitham,haitham qudaih,code,javascript,php,databases,entrepreneurship,startups,react,angular,javascript"
github: haithamq
medium:
twitter:
email: haithamqdaih@gmail.com

exclude: ["README.md", "CNAME", "LICENSE", ".gitignore"]
include: ["résumé.pdf"]

permalink: pretty
timezone: Asia/Abu_Dhabi

gems: []

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "base"

featured:
  - id: 1
    title: Journey to HTTP/2
    date: 2016-08-13 12:30:00
    type: light
    url: /blog/2016/08/13/http-in-depth/
  - id: 2
    title: Web Cache in Depth
    date: 2017-03-14 11:50:00
    type: light
    url: /blog/2017/03/14/quick-guide-to-http-caching/

about:
  - name: Github
    username: haithamq
    url: https://github.com/haithamq
    class: github
  - name: Linkedin
    username: haithamqudaih
    url: https://www.linkedin.com/in/haithamqudaih/
    class:linkedin
  - name: Twitter
    username: heetho_fs
    url: https://www.twitter.com/heetho_fs
    class: twitter
  - name: Email
    username: haithamqdaih@gmail.com
    class: email
    url: mailto:haithamqdaih@gmail.com
