title: Haitham Qudaih
description: "Front End Developer at tajawal — tech guy with an entrepreneurial spirit and knack for getting things done"
url: "https://haithamq.github.io"
author: "Haitham Qudaih"
keywords: "haitham,haitham qudaih,code,javascript,php,databases,entrepreneurship,startups,react,angular,javascript"
github: haithamq
medium:
twitter: heetho_fs
email: haithamqdaih@gmail.com

exclude: ["README.md", "CNAME", "LICENSE", ".gitignore"]
include: ["résumé.pdf"]

permalink: pretty
timezone: Asia/Abu_Dhabi

gems: []

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "base"

about:
  - name: Github
    username: haithamq
    url: https://github.com/haithamq
    class: github
  - name: Linkedin
    username: haithamqudaih
    url: https://www.linkedin.com/in/haithamqudaih/
    class: linkedin
  - name: Twitter
    username: heetho_fs
    url: https://www.twitter.com/heetho_fs
    class: twitter
    name: Twitter
    username: @haithamqdaih
    url: https://medium.com/@haithamqdaih
    class: medium
  - name: Email
    username: haithamqdaih@gmail.com
    class: email
    url: mailto:haithamqdaih@gmail.com
